* Zeitschrift Luxemburg Gesprach mit Arne Behrensen

  - Lastenräder bieten eine echte Alternative zum privaten oder gewerblichen Auto. Das gilt insbesondere für kleine Transporte im städtischen Raum.
  - Laut einer Studie des europäischen Cyclelogistics-Projekts könnten 51 Prozent aller motorisierten Transporte in europäischen Städten auf Fahrräder bzw. Lastenräder verlagert werden (Reiter/Wrighton 2014).
  - zwei Drittel der Transporte sind private Fahrten
  - In Kopenhagen und Amsterdam hat das private Auto in den Innenstädten seine hegemoniale Stellung längst verloren.
  - Regelmäßig kursieren auch Bilder von Mitgliedern der Königsfamilien auf Lastenrädern.
  - Autofreie Städte werden so erst konkret vorstellbar.

* Cargo bikes as a growth area for bicycle vs. auto trips: Exploring the potential for mode substitution behavior

 - 68.9% aller Befragten haben ihr Verhalten bezügich Transport geändert nachdem sie ein Lastenrad erworben haben.
 - 1-2 Autofahrten pro Tag konnten reduziert werden

* Exploring the Potential of Free Cargo-Bikesharing for Sustainable Mobility

  - 46% der Befragten gaben an Fahrten mit dem Auto zu erledigen, wenn das Lastenrad nicht zur Verfügung stehen
  - in Deutschland könnten ein fünftel aller Fahrten mit dem Lastenrad ersetzt werden
  -
