* Zeitschrift Luxemburg Gesprach mit Arne Behrensen

  - Lastenräder bieten eine echte Alternative zum privaten oder gewerblichen Auto. Das gilt insbesondere für kleine Transporte im städtischen  Raum.
  - Laut einer Studie des europäischen Cyclelogistics-Projekts könnten 51 Prozent aller motorisierten Transporte in europäischen Städten auf Fahrräder bzw. Lastenräder verlagert werden (Reiter/Wrighton 2014).
  - zwei Drittel der Transporte sind private Fahrten
  - In Kopenhagen und Amsterdam hat das private Auto in den Innenstädten seine hegemoniale Stellung längst verloren.
  - Regelmäßig kursieren auch Bilder von Mitgliedern der Königsfamilien auf Lastenrädern.
  - Autofreie Städte werden so erst konkret vorstellbar.

* Cargo bikes as a growth area for bicycle vs. auto trips: Exploring the potential for mode substitution behavior

 - 68.9% aller Befragten haben ihr Verhalten bezügich Transport geändert nachdem sie ein Lastenrad erworben haben.
 - 1-2 Autofahrten pro Tag konnten reduziert werden

* Exploring the Potential of Free Cargo-Bikesharing for Sustainable Mobility

  - 46% der Befragten gaben an Fahrten mit dem Auto zu erledigen, wenn das Lastenrad nicht zur Verfügung stehen
  - in Deutschland könnten ein fünftel aller Fahrten mit dem Lastenrad ersetzt werden
  -


* Warum das  Bullitt?

  - lange überlegt: Was ist die eierlegende wollmilchsau
  - bullitt vereint: leicht und gleichzeizig viel Kapazität
  - zbugänglich für ungeübt radfahrerInnen
  - lässt sich auf alle größen leicht verstellen
  - wächst mit den ansprüchen mit
  - qualitativ sehr hochwertig
  - hat eine lange geschichte
  - lässt sich als e- varinate auch ohne motor fahren
  - macht spaß, schickes design ;););)
  - nicht primär für den kindertransport sondern für Lasten ( kann aber auch kurzerhand Kinder transportieren)
  - es ist schmal und wendig und damit für den stadtverkehr gut geeignet
  - erfolgsgeschichten und impressionnen zum bullit


* Was ist besonders am Veedelvelo?

  - nachbarschaftsvernetzung, erreicht eher menschen die vorher nicht so viel
    rad gefahren sind, durch persönliche Kontakte
  - schafft zusätzliche vernetzung
  - dezentrale organiserung
  - ??? wie machen wir das bekannt??? Verteiler, Flyer, MundzuMund
  - geringe eintrittbarrieren, keine versicherung
  - vernetzung mit anderen
  - übersicht andere lastenräder
